"""fixed crop yield model

Revision ID: 486d0df15321
Revises: 668fd4895f06
Create Date: 2022-11-01 23:43:55.607489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486d0df15321'
down_revision = '668fd4895f06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
