"""Added weather stats

Revision ID: a62167fda476
Revises: 486d0df15321
Create Date: 2022-11-02 16:12:27.515506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a62167fda476"
down_revision = "486d0df15321"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "station_weather_summary",
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("station", sa.String(length=11), nullable=False),
        sa.Column("average_min_temperature", sa.Float(), nullable=True),
        sa.Column("average_max_temperature", sa.Float(), nullable=True),
        sa.Column("total_precipitation", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("year", "station"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("station_weather_summary")
    # ### end Alembic commands ###
